spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/jpaPractice
    password: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true